### ISSUE TITLE
Publish to PowerShell Gallery

### ISSUE THREAD

**Issue by csr-nick** [DHowett/DirColors#6]
This module is awesome. Any chance you could publish to the [PS Gallery](https://www.powershellgallery.com/packages/upload)?

**Comment by DHowett** [comment]
Absolutely. Stay tuned, and thank you!

**Comment by DHowett** [comment]
https://www.powershellgallery.com/packages/DirColors/1.0.0

Deployed via:
https://gitlab.howett.net/powershell/DirColors/-/jobs/192

**Comment by csr-nick** [comment]
Fantastic. Thanks so much!
